
Tue, 04 Feb 2020 18:50:31 GMT

COMMAND LINE:
/opt/src/Python-3.8.0/bin/python3 nbody.python 10000

PROGRAM FAILED 


PROGRAM OUTPUT:
-0.169075164

Traceback (most recent call last):
  File "nbody.python", line 110, in <module>
    main(int(sys.argv[1]))
  File "nbody.python", line 106, in main
    advance(0.01, n)
  File "nbody.python", line 56, in advance
    for i in xrange(n):
NameError: name 'xrange' is not defined
